#!/bin/sh

rm -rf quip-api-java
git clone git@github.com:kenichi-ando/quip-api-java.git
cd quip-api-java && mvn package -DskipTests
mv target/quip-api-client-jar-with-dependencies.jar ../quip.jar
cd .. && rm -rf quip-api-java
